set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP TRUE)
include(InstallRequiredSystemLibraries)
install(PROGRAMS ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS}
        DESTINATION "."
        COMPONENT bomberman_app)
install(TARGETS OpenAL
        DESTINATION "."
        COMPONENT bomberman_app)

# installer rules.
set(CPACK_NSIS_DISPLAY_NAME "Bomberman")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A 3D Bomberman")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Bomberman")
set(CPACK_PACKAGE_NAME "Bomberman")
set(CPACK_PACKAGE_VENDOR "Indie")
set(CPACK_PACKAGE_VERSION ${PROJECT_VER})
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VER_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VER_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VER_PATCH})
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Indie\\\\Bomberman")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Bomberman")
set(CPACK_NSIS_MODIFY_PATH ON)

set(CPACK_COMPONENTS_ALL bomberman_app)
set(CPACK_COMPONENT_BOMBERMAN_APP_REQUIRED TRUE)
set(CPACK_PACKAGE_EXECUTABLES "bomberman;Bomberman")
set(CPACK_CREATE_DESKTOP_LINKS "bomberman")

set(CPACK_STRIP_FILES "bomberman.exe")

set(CPACK_COMPONENTS_ALL bomberman_app)
set(CPACK_COMPONENT_BOMBERMAN_APP_DISPLAY_NAME "Bomberman")

set(CPACK_PACKAGE_ICON "${CMAKE_CURRENT_SOURCE_DIR}\\\\CMake\\\\bomberman.png")
set(CPACK_NSIS_MUI_ICON "${CMAKE_CURRENT_SOURCE_DIR}/CMake/bomberman.ico")
set(CPACK_NSIS_MUI_UNIICON "${CMAKE_CURRENT_SOURCE_DIR}/CMake/bomberman.ico")
set(CPACK_NSIS_INSTALLED_ICON_NAME "bomberman.exe")

set(CPACK_NSIS_EXECUTABLES_DIRECTORY ".")
set(CPACK_NSIS_DISPLAY_NAME "Bomberman")

include(CPack)
