name: Build - Develop

on:
  push:
    branches: [ develop ]

jobs:
  build-epitest:

    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker

    steps:
    - uses: actions/checkout@v2

    - name: "Build"
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -B build
        cmake --build build

    - name: "Check file existence"
      run: |
        test -f bomberman
